acmeair-nginx1:
  container_name: acmeair-nginx1
  net: ${NETWORK}
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes:
    - /www/public
  volumes_from:
    - acmeair-mainservice-java
    - acmeair-authservice-java
    - acmeair-bookingservice-java
    - acmeair-customerservice-java
    - acmeair-flightservice-java

acmeair-mainservice-java:
  container_name: acmeair-mainservice-java
  dockerfile: Dockerfile
  net: ${NETWORK}
  build: ../acmeair-mainservice-java/
  mem_limit: 512m

acmeair-authservice-java:
  container_name: acmeair-authservice-java
  dockerfile: Dockerfile
  net: ${NETWORK}
  build: ../acmeair-authservice-java/
  environment:
    - ACMEAIR_STACKAA_CUSTOMER_URL=http://acmeair-nginx1/customer
  mem_limit: 512m

acmeair-bookingservice-java:
  container_name: acmeair-bookingservice-java
  dockerfile: Dockerfile
  net: ${NETWORK}
  build: ../acmeair-bookingservice-java/
  environment:
    - MONGO_HOST=192.168.90.82
    - ACMEAIR_STACKAA_AUTH_URL=http://acmeair-nginx1/auth
    - ACMEAIR_STACKAA_CUSTOMER_URL=http://acmeair-nginx1/customer
    - ACMEAIR_STACKAA_FLIGHT_URL=http://acmeair-nginx1/flight
  mem_limit: 512m

acmeair-customerservice-java:
  container_name: acmeair-customerservice-java
  dockerfile: Dockerfile
  net: ${NETWORK}
  build: ../acmeair-customerservice-java/
  environment:
    - MONGO_HOST=192.168.90.82
    - ACMEAIR_STACKAA_AUTH_URL=http://acmeair-nginx1/auth
  mem_limit: 512m

acmeair-flightservice-java:
  container_name: acmeair-flightservice-java
  dockerfile: Dockerfile
  net: ${NETWORK}
  build: ../acmeair-flightservice-java/
  environment:
    - MONGO_HOST=192.168.90.82
  mem_limit: 512m
