acmeair-nginx1:
  container_name: acmeair-nginx1
  net: ${NETWORK}
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes:
    - /www/public
  volumes_from:
    - acmeair-mainservice-java
    - acmeair-authservice-java
    - acmeair-bookingservice-java
    - acmeair-bookingservice-java-2
    - acmeair-customerservice-java
    - acmeair-flightservice-java

acmeair-mainservice-java:
  container_name: acmeair-mainservice-java
  dockerfile: Dockerfile-wf
  net: ${NETWORK}
  build: ../acmeair-mainservice-java/
  cpuset: 2-3
  mem_limit: 1g

acmeair-authservice-java:
  container_name: acmeair-authservice-java
  dockerfile: Dockerfile-wf
  net: ${NETWORK}
  build: ../acmeair-authservice-java/
  cpuset: 4-5
  mem_limit: 1g

acmeair-bookingservice-java:
  container_name: acmeair-bookingservice-java
  dockerfile: Dockerfile-wf
  net: ${NETWORK}
  build: ../acmeair-bookingservice-java/
  environment:
    - MONGO_HOST=192.168.90.82
  cpuset: 6-7
  mem_limit: 1g

acmeair-bookingservice-java-2:
  container_name: acmeair-bookingservice-java-2
  dockerfile: Dockerfile-wf
  net: ${NETWORK}
  build: ../acmeair-bookingservice-java/
  environment:
    - MONGO_HOST=192.168.90.82
  cpuset: 8-9
  mem_limit: 1g

acmeair-customerservice-java:
  container_name: acmeair-customerservice-java
  dockerfile: Dockerfile-wf
  net: ${NETWORK}
  build: ../acmeair-customerservice-java/
  environment:
    - MONGO_HOST=192.168.90.82
  cpuset: 10-11
  mem_limit: 1g

acmeair-flightservice-java:
  container_name: acmeair-flightservice-java
  dockerfile: Dockerfile-wf
  net: ${NETWORK}
  build: ../acmeair-flightservice-java/
  environment:
    - MONGO_HOST=192.168.90.82
  cpuset: 12-13
  mem_limit: 1g
